// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

/**
 * Protobuf type {@code qubic.archiver.archive.pb.Computors}
 */
public final class Computors extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qubic.archiver.archive.pb.Computors)
    ComputorsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Computors.newBuilder() to construct.
  private Computors(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Computors() {
    identities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    signatureHex_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Computors();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Computors(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            epoch_ = input.readUInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              identities_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            identities_.add(s);
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            signatureHex_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        identities_ = identities_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_Computors_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_Computors_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Computors.class, Builder.class);
  }

  public static final int EPOCH_FIELD_NUMBER = 1;
  private int epoch_;
  /**
   * <code>uint32 epoch = 1;</code>
   * @return The epoch.
   */
  @Override
  public int getEpoch() {
    return epoch_;
  }

  public static final int IDENTITIES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList identities_;
  /**
   * <code>repeated string identities = 2;</code>
   * @return A list containing the identities.
   */
  public com.google.protobuf.ProtocolStringList
      getIdentitiesList() {
    return identities_;
  }
  /**
   * <code>repeated string identities = 2;</code>
   * @return The count of identities.
   */
  public int getIdentitiesCount() {
    return identities_.size();
  }
  /**
   * <code>repeated string identities = 2;</code>
   * @param index The index of the element to return.
   * @return The identities at the given index.
   */
  public String getIdentities(int index) {
    return identities_.get(index);
  }
  /**
   * <code>repeated string identities = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the identities at the given index.
   */
  public com.google.protobuf.ByteString
      getIdentitiesBytes(int index) {
    return identities_.getByteString(index);
  }

  public static final int SIGNATURE_HEX_FIELD_NUMBER = 3;
  private volatile Object signatureHex_;
  /**
   * <code>string signature_hex = 3;</code>
   * @return The signatureHex.
   */
  @Override
  public String getSignatureHex() {
    Object ref = signatureHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      signatureHex_ = s;
      return s;
    }
  }
  /**
   * <code>string signature_hex = 3;</code>
   * @return The bytes for signatureHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSignatureHexBytes() {
    Object ref = signatureHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      signatureHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (epoch_ != 0) {
      output.writeUInt32(1, epoch_);
    }
    for (int i = 0; i < identities_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, identities_.getRaw(i));
    }
    if (!getSignatureHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, signatureHex_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (epoch_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, epoch_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < identities_.size(); i++) {
        dataSize += computeStringSizeNoTag(identities_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIdentitiesList().size();
    }
    if (!getSignatureHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, signatureHex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Computors)) {
      return super.equals(obj);
    }
    Computors other = (Computors) obj;

    if (getEpoch()
        != other.getEpoch()) return false;
    if (!getIdentitiesList()
        .equals(other.getIdentitiesList())) return false;
    if (!getSignatureHex()
        .equals(other.getSignatureHex())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + getEpoch();
    if (getIdentitiesCount() > 0) {
      hash = (37 * hash) + IDENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getIdentitiesList().hashCode();
    }
    hash = (37 * hash) + SIGNATURE_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureHex().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Computors parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Computors parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Computors parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Computors parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Computors parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Computors parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Computors parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Computors parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Computors parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Computors parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Computors parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Computors parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Computors prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qubic.archiver.archive.pb.Computors}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qubic.archiver.archive.pb.Computors)
      ComputorsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_Computors_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_Computors_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Computors.class, Builder.class);
    }

    // Construct using org.qubic.archiver.proto.Computors.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      epoch_ = 0;

      identities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      signatureHex_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_Computors_descriptor;
    }

    @Override
    public Computors getDefaultInstanceForType() {
      return Computors.getDefaultInstance();
    }

    @Override
    public Computors build() {
      Computors result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Computors buildPartial() {
      Computors result = new Computors(this);
      int from_bitField0_ = bitField0_;
      result.epoch_ = epoch_;
      if (((bitField0_ & 0x00000001) != 0)) {
        identities_ = identities_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.identities_ = identities_;
      result.signatureHex_ = signatureHex_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Computors) {
        return mergeFrom((Computors)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Computors other) {
      if (other == Computors.getDefaultInstance()) return this;
      if (other.getEpoch() != 0) {
        setEpoch(other.getEpoch());
      }
      if (!other.identities_.isEmpty()) {
        if (identities_.isEmpty()) {
          identities_ = other.identities_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIdentitiesIsMutable();
          identities_.addAll(other.identities_);
        }
        onChanged();
      }
      if (!other.getSignatureHex().isEmpty()) {
        signatureHex_ = other.signatureHex_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Computors parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Computors) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int epoch_ ;
    /**
     * <code>uint32 epoch = 1;</code>
     * @return The epoch.
     */
    @Override
    public int getEpoch() {
      return epoch_;
    }
    /**
     * <code>uint32 epoch = 1;</code>
     * @param value The epoch to set.
     * @return This builder for chaining.
     */
    public Builder setEpoch(int value) {
      
      epoch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 epoch = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpoch() {
      
      epoch_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList identities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIdentitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        identities_ = new com.google.protobuf.LazyStringArrayList(identities_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @return A list containing the identities.
     */
    public com.google.protobuf.ProtocolStringList
        getIdentitiesList() {
      return identities_.getUnmodifiableView();
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @return The count of identities.
     */
    public int getIdentitiesCount() {
      return identities_.size();
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @param index The index of the element to return.
     * @return The identities at the given index.
     */
    public String getIdentities(int index) {
      return identities_.get(index);
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the identities at the given index.
     */
    public com.google.protobuf.ByteString
        getIdentitiesBytes(int index) {
      return identities_.getByteString(index);
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @param index The index to set the value at.
     * @param value The identities to set.
     * @return This builder for chaining.
     */
    public Builder setIdentities(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdentitiesIsMutable();
      identities_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @param value The identities to add.
     * @return This builder for chaining.
     */
    public Builder addIdentities(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdentitiesIsMutable();
      identities_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @param values The identities to add.
     * @return This builder for chaining.
     */
    public Builder addAllIdentities(
        Iterable<String> values) {
      ensureIdentitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, identities_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentities() {
      identities_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string identities = 2;</code>
     * @param value The bytes of the identities to add.
     * @return This builder for chaining.
     */
    public Builder addIdentitiesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIdentitiesIsMutable();
      identities_.add(value);
      onChanged();
      return this;
    }

    private Object signatureHex_ = "";
    /**
     * <code>string signature_hex = 3;</code>
     * @return The signatureHex.
     */
    public String getSignatureHex() {
      Object ref = signatureHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signatureHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string signature_hex = 3;</code>
     * @return The bytes for signatureHex.
     */
    public com.google.protobuf.ByteString
        getSignatureHexBytes() {
      Object ref = signatureHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signatureHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string signature_hex = 3;</code>
     * @param value The signatureHex to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string signature_hex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignatureHex() {
      
      signatureHex_ = getDefaultInstance().getSignatureHex();
      onChanged();
      return this;
    }
    /**
     * <code>string signature_hex = 3;</code>
     * @param value The bytes for signatureHex to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signatureHex_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qubic.archiver.archive.pb.Computors)
  }

  // @@protoc_insertion_point(class_scope:qubic.archiver.archive.pb.Computors)
  private static final Computors DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Computors();
  }

  public static Computors getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Computors>
      PARSER = new com.google.protobuf.AbstractParser<Computors>() {
    @Override
    public Computors parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Computors(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Computors> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Computors> getParserForType() {
    return PARSER;
  }

  @Override
  public Computors getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

