// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface ComputorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.Computors)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 epoch = 1;</code>
   * @return The epoch.
   */
  int getEpoch();

  /**
   * <code>repeated string identities = 2;</code>
   * @return A list containing the identities.
   */
  java.util.List<String>
      getIdentitiesList();
  /**
   * <code>repeated string identities = 2;</code>
   * @return The count of identities.
   */
  int getIdentitiesCount();
  /**
   * <code>repeated string identities = 2;</code>
   * @param index The index of the element to return.
   * @return The identities at the given index.
   */
  String getIdentities(int index);
  /**
   * <code>repeated string identities = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the identities at the given index.
   */
  com.google.protobuf.ByteString
      getIdentitiesBytes(int index);

  /**
   * <code>string signature_hex = 3;</code>
   * @return The signatureHex.
   */
  String getSignatureHex();
  /**
   * <code>string signature_hex = 3;</code>
   * @return The bytes for signatureHex.
   */
  com.google.protobuf.ByteString
      getSignatureHexBytes();
}
