// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetLatestTickResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetLatestTickResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 latest_tick = 1;</code>
   * @return The latestTick.
   */
  int getLatestTick();
}
