// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetQuorumTickDataResponseStoredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetQuorumTickDataResponseStored)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
   * @return Whether the quorumTickData field is set.
   */
  boolean hasQuorumTickData();
  /**
   * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
   * @return The quorumTickData.
   */
  org.qubic.archiver.proto.QuorumTickDataStored getQuorumTickData();
  /**
   * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
   */
  org.qubic.archiver.proto.QuorumTickDataStoredOrBuilder getQuorumTickDataOrBuilder();
}
