// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

/**
 * Protobuf type {@code qubic.archiver.archive.pb.GetQuorumTickDataResponseStored}
 */
public final class GetQuorumTickDataResponseStored extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qubic.archiver.archive.pb.GetQuorumTickDataResponseStored)
    GetQuorumTickDataResponseStoredOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetQuorumTickDataResponseStored.newBuilder() to construct.
  private GetQuorumTickDataResponseStored(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetQuorumTickDataResponseStored() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetQuorumTickDataResponseStored();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetQuorumTickDataResponseStored(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.qubic.archiver.proto.QuorumTickDataStored.Builder subBuilder = null;
            if (quorumTickData_ != null) {
              subBuilder = quorumTickData_.toBuilder();
            }
            quorumTickData_ = input.readMessage(org.qubic.archiver.proto.QuorumTickDataStored.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(quorumTickData_);
              quorumTickData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetQuorumTickDataResponseStored_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetQuorumTickDataResponseStored_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qubic.archiver.proto.GetQuorumTickDataResponseStored.class, org.qubic.archiver.proto.GetQuorumTickDataResponseStored.Builder.class);
  }

  public static final int QUORUM_TICK_DATA_FIELD_NUMBER = 1;
  private org.qubic.archiver.proto.QuorumTickDataStored quorumTickData_;
  /**
   * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
   * @return Whether the quorumTickData field is set.
   */
  @java.lang.Override
  public boolean hasQuorumTickData() {
    return quorumTickData_ != null;
  }
  /**
   * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
   * @return The quorumTickData.
   */
  @java.lang.Override
  public org.qubic.archiver.proto.QuorumTickDataStored getQuorumTickData() {
    return quorumTickData_ == null ? org.qubic.archiver.proto.QuorumTickDataStored.getDefaultInstance() : quorumTickData_;
  }
  /**
   * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
   */
  @java.lang.Override
  public org.qubic.archiver.proto.QuorumTickDataStoredOrBuilder getQuorumTickDataOrBuilder() {
    return getQuorumTickData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (quorumTickData_ != null) {
      output.writeMessage(1, getQuorumTickData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (quorumTickData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getQuorumTickData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qubic.archiver.proto.GetQuorumTickDataResponseStored)) {
      return super.equals(obj);
    }
    org.qubic.archiver.proto.GetQuorumTickDataResponseStored other = (org.qubic.archiver.proto.GetQuorumTickDataResponseStored) obj;

    if (hasQuorumTickData() != other.hasQuorumTickData()) return false;
    if (hasQuorumTickData()) {
      if (!getQuorumTickData()
          .equals(other.getQuorumTickData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasQuorumTickData()) {
      hash = (37 * hash) + QUORUM_TICK_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getQuorumTickData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qubic.archiver.proto.GetQuorumTickDataResponseStored prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qubic.archiver.archive.pb.GetQuorumTickDataResponseStored}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qubic.archiver.archive.pb.GetQuorumTickDataResponseStored)
      org.qubic.archiver.proto.GetQuorumTickDataResponseStoredOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetQuorumTickDataResponseStored_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetQuorumTickDataResponseStored_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qubic.archiver.proto.GetQuorumTickDataResponseStored.class, org.qubic.archiver.proto.GetQuorumTickDataResponseStored.Builder.class);
    }

    // Construct using org.qubic.archiver.proto.GetQuorumTickDataResponseStored.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (quorumTickDataBuilder_ == null) {
        quorumTickData_ = null;
      } else {
        quorumTickData_ = null;
        quorumTickDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetQuorumTickDataResponseStored_descriptor;
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetQuorumTickDataResponseStored getDefaultInstanceForType() {
      return org.qubic.archiver.proto.GetQuorumTickDataResponseStored.getDefaultInstance();
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetQuorumTickDataResponseStored build() {
      org.qubic.archiver.proto.GetQuorumTickDataResponseStored result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetQuorumTickDataResponseStored buildPartial() {
      org.qubic.archiver.proto.GetQuorumTickDataResponseStored result = new org.qubic.archiver.proto.GetQuorumTickDataResponseStored(this);
      if (quorumTickDataBuilder_ == null) {
        result.quorumTickData_ = quorumTickData_;
      } else {
        result.quorumTickData_ = quorumTickDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qubic.archiver.proto.GetQuorumTickDataResponseStored) {
        return mergeFrom((org.qubic.archiver.proto.GetQuorumTickDataResponseStored)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qubic.archiver.proto.GetQuorumTickDataResponseStored other) {
      if (other == org.qubic.archiver.proto.GetQuorumTickDataResponseStored.getDefaultInstance()) return this;
      if (other.hasQuorumTickData()) {
        mergeQuorumTickData(other.getQuorumTickData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qubic.archiver.proto.GetQuorumTickDataResponseStored parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qubic.archiver.proto.GetQuorumTickDataResponseStored) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.qubic.archiver.proto.QuorumTickDataStored quorumTickData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qubic.archiver.proto.QuorumTickDataStored, org.qubic.archiver.proto.QuorumTickDataStored.Builder, org.qubic.archiver.proto.QuorumTickDataStoredOrBuilder> quorumTickDataBuilder_;
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     * @return Whether the quorumTickData field is set.
     */
    public boolean hasQuorumTickData() {
      return quorumTickDataBuilder_ != null || quorumTickData_ != null;
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     * @return The quorumTickData.
     */
    public org.qubic.archiver.proto.QuorumTickDataStored getQuorumTickData() {
      if (quorumTickDataBuilder_ == null) {
        return quorumTickData_ == null ? org.qubic.archiver.proto.QuorumTickDataStored.getDefaultInstance() : quorumTickData_;
      } else {
        return quorumTickDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    public Builder setQuorumTickData(org.qubic.archiver.proto.QuorumTickDataStored value) {
      if (quorumTickDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        quorumTickData_ = value;
        onChanged();
      } else {
        quorumTickDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    public Builder setQuorumTickData(
        org.qubic.archiver.proto.QuorumTickDataStored.Builder builderForValue) {
      if (quorumTickDataBuilder_ == null) {
        quorumTickData_ = builderForValue.build();
        onChanged();
      } else {
        quorumTickDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    public Builder mergeQuorumTickData(org.qubic.archiver.proto.QuorumTickDataStored value) {
      if (quorumTickDataBuilder_ == null) {
        if (quorumTickData_ != null) {
          quorumTickData_ =
            org.qubic.archiver.proto.QuorumTickDataStored.newBuilder(quorumTickData_).mergeFrom(value).buildPartial();
        } else {
          quorumTickData_ = value;
        }
        onChanged();
      } else {
        quorumTickDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    public Builder clearQuorumTickData() {
      if (quorumTickDataBuilder_ == null) {
        quorumTickData_ = null;
        onChanged();
      } else {
        quorumTickData_ = null;
        quorumTickDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    public org.qubic.archiver.proto.QuorumTickDataStored.Builder getQuorumTickDataBuilder() {
      
      onChanged();
      return getQuorumTickDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    public org.qubic.archiver.proto.QuorumTickDataStoredOrBuilder getQuorumTickDataOrBuilder() {
      if (quorumTickDataBuilder_ != null) {
        return quorumTickDataBuilder_.getMessageOrBuilder();
      } else {
        return quorumTickData_ == null ?
            org.qubic.archiver.proto.QuorumTickDataStored.getDefaultInstance() : quorumTickData_;
      }
    }
    /**
     * <code>.qubic.archiver.archive.pb.QuorumTickDataStored quorum_tick_data = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qubic.archiver.proto.QuorumTickDataStored, org.qubic.archiver.proto.QuorumTickDataStored.Builder, org.qubic.archiver.proto.QuorumTickDataStoredOrBuilder> 
        getQuorumTickDataFieldBuilder() {
      if (quorumTickDataBuilder_ == null) {
        quorumTickDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qubic.archiver.proto.QuorumTickDataStored, org.qubic.archiver.proto.QuorumTickDataStored.Builder, org.qubic.archiver.proto.QuorumTickDataStoredOrBuilder>(
                getQuorumTickData(),
                getParentForChildren(),
                isClean());
        quorumTickData_ = null;
      }
      return quorumTickDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qubic.archiver.archive.pb.GetQuorumTickDataResponseStored)
  }

  // @@protoc_insertion_point(class_scope:qubic.archiver.archive.pb.GetQuorumTickDataResponseStored)
  private static final org.qubic.archiver.proto.GetQuorumTickDataResponseStored DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qubic.archiver.proto.GetQuorumTickDataResponseStored();
  }

  public static org.qubic.archiver.proto.GetQuorumTickDataResponseStored getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetQuorumTickDataResponseStored>
      PARSER = new com.google.protobuf.AbstractParser<GetQuorumTickDataResponseStored>() {
    @java.lang.Override
    public GetQuorumTickDataResponseStored parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetQuorumTickDataResponseStored(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetQuorumTickDataResponseStored> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetQuorumTickDataResponseStored> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qubic.archiver.proto.GetQuorumTickDataResponseStored getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

