// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetSendManyTransactionResponseV2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetSendManyTransactionResponseV2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
   * @return Whether the transaction field is set.
   */
  boolean hasTransaction();
  /**
   * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
   * @return The transaction.
   */
  org.qubic.archiver.proto.SendManyTransaction getTransaction();
  /**
   * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
   */
  org.qubic.archiver.proto.SendManyTransactionOrBuilder getTransactionOrBuilder();

  /**
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>bool money_flew = 4;</code>
   * @return The moneyFlew.
   */
  boolean getMoneyFlew();
}
