// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

/**
 * Protobuf type {@code qubic.archiver.archive.pb.GetSendManyTransactionResponseV2}
 */
public final class GetSendManyTransactionResponseV2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qubic.archiver.archive.pb.GetSendManyTransactionResponseV2)
    GetSendManyTransactionResponseV2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSendManyTransactionResponseV2.newBuilder() to construct.
  private GetSendManyTransactionResponseV2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSendManyTransactionResponseV2() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSendManyTransactionResponseV2();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetSendManyTransactionResponseV2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            org.qubic.archiver.proto.SendManyTransaction.Builder subBuilder = null;
            if (transaction_ != null) {
              subBuilder = transaction_.toBuilder();
            }
            transaction_ = input.readMessage(org.qubic.archiver.proto.SendManyTransaction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transaction_);
              transaction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 32: {

            moneyFlew_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetSendManyTransactionResponseV2_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetSendManyTransactionResponseV2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qubic.archiver.proto.GetSendManyTransactionResponseV2.class, org.qubic.archiver.proto.GetSendManyTransactionResponseV2.Builder.class);
  }

  public static final int TRANSACTION_FIELD_NUMBER = 2;
  private org.qubic.archiver.proto.SendManyTransaction transaction_;
  /**
   * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
   * @return Whether the transaction field is set.
   */
  @java.lang.Override
  public boolean hasTransaction() {
    return transaction_ != null;
  }
  /**
   * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
   * @return The transaction.
   */
  @java.lang.Override
  public org.qubic.archiver.proto.SendManyTransaction getTransaction() {
    return transaction_ == null ? org.qubic.archiver.proto.SendManyTransaction.getDefaultInstance() : transaction_;
  }
  /**
   * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
   */
  @java.lang.Override
  public org.qubic.archiver.proto.SendManyTransactionOrBuilder getTransactionOrBuilder() {
    return getTransaction();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int MONEY_FLEW_FIELD_NUMBER = 4;
  private boolean moneyFlew_;
  /**
   * <code>bool money_flew = 4;</code>
   * @return The moneyFlew.
   */
  @java.lang.Override
  public boolean getMoneyFlew() {
    return moneyFlew_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transaction_ != null) {
      output.writeMessage(2, getTransaction());
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(3, timestamp_);
    }
    if (moneyFlew_ != false) {
      output.writeBool(4, moneyFlew_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transaction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTransaction());
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timestamp_);
    }
    if (moneyFlew_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, moneyFlew_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qubic.archiver.proto.GetSendManyTransactionResponseV2)) {
      return super.equals(obj);
    }
    org.qubic.archiver.proto.GetSendManyTransactionResponseV2 other = (org.qubic.archiver.proto.GetSendManyTransactionResponseV2) obj;

    if (hasTransaction() != other.hasTransaction()) return false;
    if (hasTransaction()) {
      if (!getTransaction()
          .equals(other.getTransaction())) return false;
    }
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getMoneyFlew()
        != other.getMoneyFlew()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTransaction()) {
      hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getTransaction().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + MONEY_FLEW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMoneyFlew());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qubic.archiver.proto.GetSendManyTransactionResponseV2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qubic.archiver.archive.pb.GetSendManyTransactionResponseV2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qubic.archiver.archive.pb.GetSendManyTransactionResponseV2)
      org.qubic.archiver.proto.GetSendManyTransactionResponseV2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetSendManyTransactionResponseV2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetSendManyTransactionResponseV2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qubic.archiver.proto.GetSendManyTransactionResponseV2.class, org.qubic.archiver.proto.GetSendManyTransactionResponseV2.Builder.class);
    }

    // Construct using org.qubic.archiver.proto.GetSendManyTransactionResponseV2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transactionBuilder_ == null) {
        transaction_ = null;
      } else {
        transaction_ = null;
        transactionBuilder_ = null;
      }
      timestamp_ = 0L;

      moneyFlew_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetSendManyTransactionResponseV2_descriptor;
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetSendManyTransactionResponseV2 getDefaultInstanceForType() {
      return org.qubic.archiver.proto.GetSendManyTransactionResponseV2.getDefaultInstance();
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetSendManyTransactionResponseV2 build() {
      org.qubic.archiver.proto.GetSendManyTransactionResponseV2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetSendManyTransactionResponseV2 buildPartial() {
      org.qubic.archiver.proto.GetSendManyTransactionResponseV2 result = new org.qubic.archiver.proto.GetSendManyTransactionResponseV2(this);
      if (transactionBuilder_ == null) {
        result.transaction_ = transaction_;
      } else {
        result.transaction_ = transactionBuilder_.build();
      }
      result.timestamp_ = timestamp_;
      result.moneyFlew_ = moneyFlew_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qubic.archiver.proto.GetSendManyTransactionResponseV2) {
        return mergeFrom((org.qubic.archiver.proto.GetSendManyTransactionResponseV2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qubic.archiver.proto.GetSendManyTransactionResponseV2 other) {
      if (other == org.qubic.archiver.proto.GetSendManyTransactionResponseV2.getDefaultInstance()) return this;
      if (other.hasTransaction()) {
        mergeTransaction(other.getTransaction());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getMoneyFlew() != false) {
        setMoneyFlew(other.getMoneyFlew());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qubic.archiver.proto.GetSendManyTransactionResponseV2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qubic.archiver.proto.GetSendManyTransactionResponseV2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.qubic.archiver.proto.SendManyTransaction transaction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qubic.archiver.proto.SendManyTransaction, org.qubic.archiver.proto.SendManyTransaction.Builder, org.qubic.archiver.proto.SendManyTransactionOrBuilder> transactionBuilder_;
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     * @return Whether the transaction field is set.
     */
    public boolean hasTransaction() {
      return transactionBuilder_ != null || transaction_ != null;
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     * @return The transaction.
     */
    public org.qubic.archiver.proto.SendManyTransaction getTransaction() {
      if (transactionBuilder_ == null) {
        return transaction_ == null ? org.qubic.archiver.proto.SendManyTransaction.getDefaultInstance() : transaction_;
      } else {
        return transactionBuilder_.getMessage();
      }
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    public Builder setTransaction(org.qubic.archiver.proto.SendManyTransaction value) {
      if (transactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transaction_ = value;
        onChanged();
      } else {
        transactionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    public Builder setTransaction(
        org.qubic.archiver.proto.SendManyTransaction.Builder builderForValue) {
      if (transactionBuilder_ == null) {
        transaction_ = builderForValue.build();
        onChanged();
      } else {
        transactionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    public Builder mergeTransaction(org.qubic.archiver.proto.SendManyTransaction value) {
      if (transactionBuilder_ == null) {
        if (transaction_ != null) {
          transaction_ =
            org.qubic.archiver.proto.SendManyTransaction.newBuilder(transaction_).mergeFrom(value).buildPartial();
        } else {
          transaction_ = value;
        }
        onChanged();
      } else {
        transactionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    public Builder clearTransaction() {
      if (transactionBuilder_ == null) {
        transaction_ = null;
        onChanged();
      } else {
        transaction_ = null;
        transactionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    public org.qubic.archiver.proto.SendManyTransaction.Builder getTransactionBuilder() {
      
      onChanged();
      return getTransactionFieldBuilder().getBuilder();
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    public org.qubic.archiver.proto.SendManyTransactionOrBuilder getTransactionOrBuilder() {
      if (transactionBuilder_ != null) {
        return transactionBuilder_.getMessageOrBuilder();
      } else {
        return transaction_ == null ?
            org.qubic.archiver.proto.SendManyTransaction.getDefaultInstance() : transaction_;
      }
    }
    /**
     * <code>.qubic.archiver.archive.pb.SendManyTransaction transaction = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qubic.archiver.proto.SendManyTransaction, org.qubic.archiver.proto.SendManyTransaction.Builder, org.qubic.archiver.proto.SendManyTransactionOrBuilder> 
        getTransactionFieldBuilder() {
      if (transactionBuilder_ == null) {
        transactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qubic.archiver.proto.SendManyTransaction, org.qubic.archiver.proto.SendManyTransaction.Builder, org.qubic.archiver.proto.SendManyTransactionOrBuilder>(
                getTransaction(),
                getParentForChildren(),
                isClean());
        transaction_ = null;
      }
      return transactionBuilder_;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private boolean moneyFlew_ ;
    /**
     * <code>bool money_flew = 4;</code>
     * @return The moneyFlew.
     */
    @java.lang.Override
    public boolean getMoneyFlew() {
      return moneyFlew_;
    }
    /**
     * <code>bool money_flew = 4;</code>
     * @param value The moneyFlew to set.
     * @return This builder for chaining.
     */
    public Builder setMoneyFlew(boolean value) {
      
      moneyFlew_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool money_flew = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoneyFlew() {
      
      moneyFlew_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qubic.archiver.archive.pb.GetSendManyTransactionResponseV2)
  }

  // @@protoc_insertion_point(class_scope:qubic.archiver.archive.pb.GetSendManyTransactionResponseV2)
  private static final org.qubic.archiver.proto.GetSendManyTransactionResponseV2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qubic.archiver.proto.GetSendManyTransactionResponseV2();
  }

  public static org.qubic.archiver.proto.GetSendManyTransactionResponseV2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSendManyTransactionResponseV2>
      PARSER = new com.google.protobuf.AbstractParser<GetSendManyTransactionResponseV2>() {
    @java.lang.Override
    public GetSendManyTransactionResponseV2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetSendManyTransactionResponseV2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetSendManyTransactionResponseV2> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSendManyTransactionResponseV2> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qubic.archiver.proto.GetSendManyTransactionResponseV2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

