// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetTickTransactionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetTickTransactionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 1;</code>
   */
  java.util.List<org.qubic.archiver.proto.Transaction> 
      getTransactionsList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 1;</code>
   */
  org.qubic.archiver.proto.Transaction getTransactions(int index);
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 1;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 1;</code>
   */
  java.util.List<? extends org.qubic.archiver.proto.TransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 1;</code>
   */
  org.qubic.archiver.proto.TransactionOrBuilder getTransactionsOrBuilder(
      int index);
}
