// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetTickTransactionsResponseV2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetTickTransactionsResponseV2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .qubic.archiver.archive.pb.TransactionData transactions = 1;</code>
   */
  java.util.List<org.qubic.archiver.proto.TransactionData> 
      getTransactionsList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransactionData transactions = 1;</code>
   */
  org.qubic.archiver.proto.TransactionData getTransactions(int index);
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransactionData transactions = 1;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransactionData transactions = 1;</code>
   */
  java.util.List<? extends org.qubic.archiver.proto.TransactionDataOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransactionData transactions = 1;</code>
   */
  org.qubic.archiver.proto.TransactionDataOrBuilder getTransactionsOrBuilder(
      int index);
}
