// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetTransferTransactionsPerTickResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetTransferTransactionsPerTickResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .qubic.archiver.archive.pb.TransferTransactionsPerTick transfer_transactions_per_tick = 1;</code>
   */
  java.util.List<org.qubic.archiver.proto.TransferTransactionsPerTick> 
      getTransferTransactionsPerTickList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransferTransactionsPerTick transfer_transactions_per_tick = 1;</code>
   */
  org.qubic.archiver.proto.TransferTransactionsPerTick getTransferTransactionsPerTick(int index);
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransferTransactionsPerTick transfer_transactions_per_tick = 1;</code>
   */
  int getTransferTransactionsPerTickCount();
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransferTransactionsPerTick transfer_transactions_per_tick = 1;</code>
   */
  java.util.List<? extends org.qubic.archiver.proto.TransferTransactionsPerTickOrBuilder> 
      getTransferTransactionsPerTickOrBuilderList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.TransferTransactionsPerTick transfer_transactions_per_tick = 1;</code>
   */
  org.qubic.archiver.proto.TransferTransactionsPerTickOrBuilder getTransferTransactionsPerTickOrBuilder(
      int index);
}
