// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

/**
 * Protobuf type {@code qubic.archiver.archive.pb.GetTransactionStatusResponse}
 */
public final class GetTransactionStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qubic.archiver.archive.pb.GetTransactionStatusResponse)
    GetTransactionStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTransactionStatusResponse.newBuilder() to construct.
  private GetTransactionStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTransactionStatusResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTransactionStatusResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTransactionStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.qubic.archiver.proto.TransactionStatus.Builder subBuilder = null;
            if (transactionStatus_ != null) {
              subBuilder = transactionStatus_.toBuilder();
            }
            transactionStatus_ = input.readMessage(org.qubic.archiver.proto.TransactionStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transactionStatus_);
              transactionStatus_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetTransactionStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetTransactionStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qubic.archiver.proto.GetTransactionStatusResponse.class, org.qubic.archiver.proto.GetTransactionStatusResponse.Builder.class);
  }

  public static final int TRANSACTION_STATUS_FIELD_NUMBER = 1;
  private org.qubic.archiver.proto.TransactionStatus transactionStatus_;
  /**
   * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
   * @return Whether the transactionStatus field is set.
   */
  @java.lang.Override
  public boolean hasTransactionStatus() {
    return transactionStatus_ != null;
  }
  /**
   * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
   * @return The transactionStatus.
   */
  @java.lang.Override
  public org.qubic.archiver.proto.TransactionStatus getTransactionStatus() {
    return transactionStatus_ == null ? org.qubic.archiver.proto.TransactionStatus.getDefaultInstance() : transactionStatus_;
  }
  /**
   * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
   */
  @java.lang.Override
  public org.qubic.archiver.proto.TransactionStatusOrBuilder getTransactionStatusOrBuilder() {
    return getTransactionStatus();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transactionStatus_ != null) {
      output.writeMessage(1, getTransactionStatus());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transactionStatus_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTransactionStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qubic.archiver.proto.GetTransactionStatusResponse)) {
      return super.equals(obj);
    }
    org.qubic.archiver.proto.GetTransactionStatusResponse other = (org.qubic.archiver.proto.GetTransactionStatusResponse) obj;

    if (hasTransactionStatus() != other.hasTransactionStatus()) return false;
    if (hasTransactionStatus()) {
      if (!getTransactionStatus()
          .equals(other.getTransactionStatus())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTransactionStatus()) {
      hash = (37 * hash) + TRANSACTION_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qubic.archiver.proto.GetTransactionStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qubic.archiver.proto.GetTransactionStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qubic.archiver.archive.pb.GetTransactionStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qubic.archiver.archive.pb.GetTransactionStatusResponse)
      org.qubic.archiver.proto.GetTransactionStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetTransactionStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetTransactionStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qubic.archiver.proto.GetTransactionStatusResponse.class, org.qubic.archiver.proto.GetTransactionStatusResponse.Builder.class);
    }

    // Construct using org.qubic.archiver.proto.GetTransactionStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transactionStatusBuilder_ == null) {
        transactionStatus_ = null;
      } else {
        transactionStatus_ = null;
        transactionStatusBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qubic.archiver.proto.QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_GetTransactionStatusResponse_descriptor;
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetTransactionStatusResponse getDefaultInstanceForType() {
      return org.qubic.archiver.proto.GetTransactionStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetTransactionStatusResponse build() {
      org.qubic.archiver.proto.GetTransactionStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qubic.archiver.proto.GetTransactionStatusResponse buildPartial() {
      org.qubic.archiver.proto.GetTransactionStatusResponse result = new org.qubic.archiver.proto.GetTransactionStatusResponse(this);
      if (transactionStatusBuilder_ == null) {
        result.transactionStatus_ = transactionStatus_;
      } else {
        result.transactionStatus_ = transactionStatusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qubic.archiver.proto.GetTransactionStatusResponse) {
        return mergeFrom((org.qubic.archiver.proto.GetTransactionStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qubic.archiver.proto.GetTransactionStatusResponse other) {
      if (other == org.qubic.archiver.proto.GetTransactionStatusResponse.getDefaultInstance()) return this;
      if (other.hasTransactionStatus()) {
        mergeTransactionStatus(other.getTransactionStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qubic.archiver.proto.GetTransactionStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qubic.archiver.proto.GetTransactionStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.qubic.archiver.proto.TransactionStatus transactionStatus_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qubic.archiver.proto.TransactionStatus, org.qubic.archiver.proto.TransactionStatus.Builder, org.qubic.archiver.proto.TransactionStatusOrBuilder> transactionStatusBuilder_;
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     * @return Whether the transactionStatus field is set.
     */
    public boolean hasTransactionStatus() {
      return transactionStatusBuilder_ != null || transactionStatus_ != null;
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     * @return The transactionStatus.
     */
    public org.qubic.archiver.proto.TransactionStatus getTransactionStatus() {
      if (transactionStatusBuilder_ == null) {
        return transactionStatus_ == null ? org.qubic.archiver.proto.TransactionStatus.getDefaultInstance() : transactionStatus_;
      } else {
        return transactionStatusBuilder_.getMessage();
      }
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    public Builder setTransactionStatus(org.qubic.archiver.proto.TransactionStatus value) {
      if (transactionStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transactionStatus_ = value;
        onChanged();
      } else {
        transactionStatusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    public Builder setTransactionStatus(
        org.qubic.archiver.proto.TransactionStatus.Builder builderForValue) {
      if (transactionStatusBuilder_ == null) {
        transactionStatus_ = builderForValue.build();
        onChanged();
      } else {
        transactionStatusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    public Builder mergeTransactionStatus(org.qubic.archiver.proto.TransactionStatus value) {
      if (transactionStatusBuilder_ == null) {
        if (transactionStatus_ != null) {
          transactionStatus_ =
            org.qubic.archiver.proto.TransactionStatus.newBuilder(transactionStatus_).mergeFrom(value).buildPartial();
        } else {
          transactionStatus_ = value;
        }
        onChanged();
      } else {
        transactionStatusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    public Builder clearTransactionStatus() {
      if (transactionStatusBuilder_ == null) {
        transactionStatus_ = null;
        onChanged();
      } else {
        transactionStatus_ = null;
        transactionStatusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    public org.qubic.archiver.proto.TransactionStatus.Builder getTransactionStatusBuilder() {
      
      onChanged();
      return getTransactionStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    public org.qubic.archiver.proto.TransactionStatusOrBuilder getTransactionStatusOrBuilder() {
      if (transactionStatusBuilder_ != null) {
        return transactionStatusBuilder_.getMessageOrBuilder();
      } else {
        return transactionStatus_ == null ?
            org.qubic.archiver.proto.TransactionStatus.getDefaultInstance() : transactionStatus_;
      }
    }
    /**
     * <code>.qubic.archiver.archive.pb.TransactionStatus transaction_status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qubic.archiver.proto.TransactionStatus, org.qubic.archiver.proto.TransactionStatus.Builder, org.qubic.archiver.proto.TransactionStatusOrBuilder> 
        getTransactionStatusFieldBuilder() {
      if (transactionStatusBuilder_ == null) {
        transactionStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qubic.archiver.proto.TransactionStatus, org.qubic.archiver.proto.TransactionStatus.Builder, org.qubic.archiver.proto.TransactionStatusOrBuilder>(
                getTransactionStatus(),
                getParentForChildren(),
                isClean());
        transactionStatus_ = null;
      }
      return transactionStatusBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qubic.archiver.archive.pb.GetTransactionStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:qubic.archiver.archive.pb.GetTransactionStatusResponse)
  private static final org.qubic.archiver.proto.GetTransactionStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qubic.archiver.proto.GetTransactionStatusResponse();
  }

  public static org.qubic.archiver.proto.GetTransactionStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTransactionStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTransactionStatusResponse>() {
    @java.lang.Override
    public GetTransactionStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTransactionStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTransactionStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTransactionStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qubic.archiver.proto.GetTransactionStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

