// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface GetTransactionRequestV2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.GetTransactionRequestV2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tx_id = 1;</code>
   * @return The txId.
   */
  java.lang.String getTxId();
  /**
   * <code>string tx_id = 1;</code>
   * @return The bytes for txId.
   */
  com.google.protobuf.ByteString
      getTxIdBytes();
}
