// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface ProcessedTickOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.ProcessedTick)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 tick_number = 1;</code>
   * @return The tickNumber.
   */
  int getTickNumber();

  /**
   * <code>uint32 epoch = 2;</code>
   * @return The epoch.
   */
  int getEpoch();
}
