// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface ProcessedTickIntervalsPerEpochOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.ProcessedTickIntervalsPerEpoch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 epoch = 1;</code>
   * @return The epoch.
   */
  int getEpoch();

  /**
   * <code>repeated .qubic.archiver.archive.pb.ProcessedTickInterval intervals = 2;</code>
   */
  java.util.List<org.qubic.archiver.proto.ProcessedTickInterval> 
      getIntervalsList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.ProcessedTickInterval intervals = 2;</code>
   */
  org.qubic.archiver.proto.ProcessedTickInterval getIntervals(int index);
  /**
   * <code>repeated .qubic.archiver.archive.pb.ProcessedTickInterval intervals = 2;</code>
   */
  int getIntervalsCount();
  /**
   * <code>repeated .qubic.archiver.archive.pb.ProcessedTickInterval intervals = 2;</code>
   */
  java.util.List<? extends org.qubic.archiver.proto.ProcessedTickIntervalOrBuilder> 
      getIntervalsOrBuilderList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.ProcessedTickInterval intervals = 2;</code>
   */
  org.qubic.archiver.proto.ProcessedTickIntervalOrBuilder getIntervalsOrBuilder(
      int index);
}
