// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

/**
 * Protobuf type {@code qubic.archiver.archive.pb.QuorumDiff}
 */
public final class QuorumDiff extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qubic.archiver.archive.pb.QuorumDiff)
    QuorumDiffOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuorumDiff.newBuilder() to construct.
  private QuorumDiff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuorumDiff() {
    saltedResourceTestingDigestHex_ = "";
    saltedSpectrumDigestHex_ = "";
    saltedUniverseDigestHex_ = "";
    saltedComputerDigestHex_ = "";
    expectedNextTickTxDigestHex_ = "";
    signatureHex_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuorumDiff();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuorumDiff(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            saltedResourceTestingDigestHex_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            saltedSpectrumDigestHex_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            saltedUniverseDigestHex_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            saltedComputerDigestHex_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            expectedNextTickTxDigestHex_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            signatureHex_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_QuorumDiff_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_QuorumDiff_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QuorumDiff.class, Builder.class);
  }

  public static final int SALTED_RESOURCE_TESTING_DIGEST_HEX_FIELD_NUMBER = 1;
  private volatile Object saltedResourceTestingDigestHex_;
  /**
   * <code>string salted_resource_testing_digest_hex = 1;</code>
   * @return The saltedResourceTestingDigestHex.
   */
  @Override
  public String getSaltedResourceTestingDigestHex() {
    Object ref = saltedResourceTestingDigestHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      saltedResourceTestingDigestHex_ = s;
      return s;
    }
  }
  /**
   * <code>string salted_resource_testing_digest_hex = 1;</code>
   * @return The bytes for saltedResourceTestingDigestHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSaltedResourceTestingDigestHexBytes() {
    Object ref = saltedResourceTestingDigestHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      saltedResourceTestingDigestHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALTED_SPECTRUM_DIGEST_HEX_FIELD_NUMBER = 2;
  private volatile Object saltedSpectrumDigestHex_;
  /**
   * <code>string salted_spectrum_digest_hex = 2;</code>
   * @return The saltedSpectrumDigestHex.
   */
  @Override
  public String getSaltedSpectrumDigestHex() {
    Object ref = saltedSpectrumDigestHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      saltedSpectrumDigestHex_ = s;
      return s;
    }
  }
  /**
   * <code>string salted_spectrum_digest_hex = 2;</code>
   * @return The bytes for saltedSpectrumDigestHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSaltedSpectrumDigestHexBytes() {
    Object ref = saltedSpectrumDigestHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      saltedSpectrumDigestHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALTED_UNIVERSE_DIGEST_HEX_FIELD_NUMBER = 3;
  private volatile Object saltedUniverseDigestHex_;
  /**
   * <code>string salted_universe_digest_hex = 3;</code>
   * @return The saltedUniverseDigestHex.
   */
  @Override
  public String getSaltedUniverseDigestHex() {
    Object ref = saltedUniverseDigestHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      saltedUniverseDigestHex_ = s;
      return s;
    }
  }
  /**
   * <code>string salted_universe_digest_hex = 3;</code>
   * @return The bytes for saltedUniverseDigestHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSaltedUniverseDigestHexBytes() {
    Object ref = saltedUniverseDigestHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      saltedUniverseDigestHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALTED_COMPUTER_DIGEST_HEX_FIELD_NUMBER = 4;
  private volatile Object saltedComputerDigestHex_;
  /**
   * <code>string salted_computer_digest_hex = 4;</code>
   * @return The saltedComputerDigestHex.
   */
  @Override
  public String getSaltedComputerDigestHex() {
    Object ref = saltedComputerDigestHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      saltedComputerDigestHex_ = s;
      return s;
    }
  }
  /**
   * <code>string salted_computer_digest_hex = 4;</code>
   * @return The bytes for saltedComputerDigestHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSaltedComputerDigestHexBytes() {
    Object ref = saltedComputerDigestHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      saltedComputerDigestHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPECTED_NEXT_TICK_TX_DIGEST_HEX_FIELD_NUMBER = 5;
  private volatile Object expectedNextTickTxDigestHex_;
  /**
   * <code>string expected_next_tick_tx_digest_hex = 5;</code>
   * @return The expectedNextTickTxDigestHex.
   */
  @Override
  public String getExpectedNextTickTxDigestHex() {
    Object ref = expectedNextTickTxDigestHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      expectedNextTickTxDigestHex_ = s;
      return s;
    }
  }
  /**
   * <code>string expected_next_tick_tx_digest_hex = 5;</code>
   * @return The bytes for expectedNextTickTxDigestHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getExpectedNextTickTxDigestHexBytes() {
    Object ref = expectedNextTickTxDigestHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      expectedNextTickTxDigestHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNATURE_HEX_FIELD_NUMBER = 6;
  private volatile Object signatureHex_;
  /**
   * <code>string signature_hex = 6;</code>
   * @return The signatureHex.
   */
  @Override
  public String getSignatureHex() {
    Object ref = signatureHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      signatureHex_ = s;
      return s;
    }
  }
  /**
   * <code>string signature_hex = 6;</code>
   * @return The bytes for signatureHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSignatureHexBytes() {
    Object ref = signatureHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      signatureHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSaltedResourceTestingDigestHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, saltedResourceTestingDigestHex_);
    }
    if (!getSaltedSpectrumDigestHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, saltedSpectrumDigestHex_);
    }
    if (!getSaltedUniverseDigestHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, saltedUniverseDigestHex_);
    }
    if (!getSaltedComputerDigestHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, saltedComputerDigestHex_);
    }
    if (!getExpectedNextTickTxDigestHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, expectedNextTickTxDigestHex_);
    }
    if (!getSignatureHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, signatureHex_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSaltedResourceTestingDigestHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, saltedResourceTestingDigestHex_);
    }
    if (!getSaltedSpectrumDigestHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, saltedSpectrumDigestHex_);
    }
    if (!getSaltedUniverseDigestHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, saltedUniverseDigestHex_);
    }
    if (!getSaltedComputerDigestHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, saltedComputerDigestHex_);
    }
    if (!getExpectedNextTickTxDigestHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, expectedNextTickTxDigestHex_);
    }
    if (!getSignatureHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, signatureHex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QuorumDiff)) {
      return super.equals(obj);
    }
    QuorumDiff other = (QuorumDiff) obj;

    if (!getSaltedResourceTestingDigestHex()
        .equals(other.getSaltedResourceTestingDigestHex())) return false;
    if (!getSaltedSpectrumDigestHex()
        .equals(other.getSaltedSpectrumDigestHex())) return false;
    if (!getSaltedUniverseDigestHex()
        .equals(other.getSaltedUniverseDigestHex())) return false;
    if (!getSaltedComputerDigestHex()
        .equals(other.getSaltedComputerDigestHex())) return false;
    if (!getExpectedNextTickTxDigestHex()
        .equals(other.getExpectedNextTickTxDigestHex())) return false;
    if (!getSignatureHex()
        .equals(other.getSignatureHex())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SALTED_RESOURCE_TESTING_DIGEST_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSaltedResourceTestingDigestHex().hashCode();
    hash = (37 * hash) + SALTED_SPECTRUM_DIGEST_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSaltedSpectrumDigestHex().hashCode();
    hash = (37 * hash) + SALTED_UNIVERSE_DIGEST_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSaltedUniverseDigestHex().hashCode();
    hash = (37 * hash) + SALTED_COMPUTER_DIGEST_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSaltedComputerDigestHex().hashCode();
    hash = (37 * hash) + EXPECTED_NEXT_TICK_TX_DIGEST_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getExpectedNextTickTxDigestHex().hashCode();
    hash = (37 * hash) + SIGNATURE_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureHex().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QuorumDiff parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuorumDiff parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuorumDiff parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuorumDiff parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuorumDiff parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuorumDiff parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuorumDiff parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QuorumDiff parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QuorumDiff parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QuorumDiff parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QuorumDiff parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QuorumDiff parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QuorumDiff prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qubic.archiver.archive.pb.QuorumDiff}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qubic.archiver.archive.pb.QuorumDiff)
      QuorumDiffOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_QuorumDiff_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_QuorumDiff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuorumDiff.class, Builder.class);
    }

    // Construct using org.qubic.archiver.proto.QuorumDiff.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      saltedResourceTestingDigestHex_ = "";

      saltedSpectrumDigestHex_ = "";

      saltedUniverseDigestHex_ = "";

      saltedComputerDigestHex_ = "";

      expectedNextTickTxDigestHex_ = "";

      signatureHex_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_QuorumDiff_descriptor;
    }

    @Override
    public QuorumDiff getDefaultInstanceForType() {
      return QuorumDiff.getDefaultInstance();
    }

    @Override
    public QuorumDiff build() {
      QuorumDiff result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public QuorumDiff buildPartial() {
      QuorumDiff result = new QuorumDiff(this);
      result.saltedResourceTestingDigestHex_ = saltedResourceTestingDigestHex_;
      result.saltedSpectrumDigestHex_ = saltedSpectrumDigestHex_;
      result.saltedUniverseDigestHex_ = saltedUniverseDigestHex_;
      result.saltedComputerDigestHex_ = saltedComputerDigestHex_;
      result.expectedNextTickTxDigestHex_ = expectedNextTickTxDigestHex_;
      result.signatureHex_ = signatureHex_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QuorumDiff) {
        return mergeFrom((QuorumDiff)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QuorumDiff other) {
      if (other == QuorumDiff.getDefaultInstance()) return this;
      if (!other.getSaltedResourceTestingDigestHex().isEmpty()) {
        saltedResourceTestingDigestHex_ = other.saltedResourceTestingDigestHex_;
        onChanged();
      }
      if (!other.getSaltedSpectrumDigestHex().isEmpty()) {
        saltedSpectrumDigestHex_ = other.saltedSpectrumDigestHex_;
        onChanged();
      }
      if (!other.getSaltedUniverseDigestHex().isEmpty()) {
        saltedUniverseDigestHex_ = other.saltedUniverseDigestHex_;
        onChanged();
      }
      if (!other.getSaltedComputerDigestHex().isEmpty()) {
        saltedComputerDigestHex_ = other.saltedComputerDigestHex_;
        onChanged();
      }
      if (!other.getExpectedNextTickTxDigestHex().isEmpty()) {
        expectedNextTickTxDigestHex_ = other.expectedNextTickTxDigestHex_;
        onChanged();
      }
      if (!other.getSignatureHex().isEmpty()) {
        signatureHex_ = other.signatureHex_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QuorumDiff parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QuorumDiff) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object saltedResourceTestingDigestHex_ = "";
    /**
     * <code>string salted_resource_testing_digest_hex = 1;</code>
     * @return The saltedResourceTestingDigestHex.
     */
    public String getSaltedResourceTestingDigestHex() {
      Object ref = saltedResourceTestingDigestHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        saltedResourceTestingDigestHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string salted_resource_testing_digest_hex = 1;</code>
     * @return The bytes for saltedResourceTestingDigestHex.
     */
    public com.google.protobuf.ByteString
        getSaltedResourceTestingDigestHexBytes() {
      Object ref = saltedResourceTestingDigestHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        saltedResourceTestingDigestHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salted_resource_testing_digest_hex = 1;</code>
     * @param value The saltedResourceTestingDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedResourceTestingDigestHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      saltedResourceTestingDigestHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salted_resource_testing_digest_hex = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaltedResourceTestingDigestHex() {
      
      saltedResourceTestingDigestHex_ = getDefaultInstance().getSaltedResourceTestingDigestHex();
      onChanged();
      return this;
    }
    /**
     * <code>string salted_resource_testing_digest_hex = 1;</code>
     * @param value The bytes for saltedResourceTestingDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedResourceTestingDigestHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      saltedResourceTestingDigestHex_ = value;
      onChanged();
      return this;
    }

    private Object saltedSpectrumDigestHex_ = "";
    /**
     * <code>string salted_spectrum_digest_hex = 2;</code>
     * @return The saltedSpectrumDigestHex.
     */
    public String getSaltedSpectrumDigestHex() {
      Object ref = saltedSpectrumDigestHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        saltedSpectrumDigestHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string salted_spectrum_digest_hex = 2;</code>
     * @return The bytes for saltedSpectrumDigestHex.
     */
    public com.google.protobuf.ByteString
        getSaltedSpectrumDigestHexBytes() {
      Object ref = saltedSpectrumDigestHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        saltedSpectrumDigestHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salted_spectrum_digest_hex = 2;</code>
     * @param value The saltedSpectrumDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedSpectrumDigestHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      saltedSpectrumDigestHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salted_spectrum_digest_hex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaltedSpectrumDigestHex() {
      
      saltedSpectrumDigestHex_ = getDefaultInstance().getSaltedSpectrumDigestHex();
      onChanged();
      return this;
    }
    /**
     * <code>string salted_spectrum_digest_hex = 2;</code>
     * @param value The bytes for saltedSpectrumDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedSpectrumDigestHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      saltedSpectrumDigestHex_ = value;
      onChanged();
      return this;
    }

    private Object saltedUniverseDigestHex_ = "";
    /**
     * <code>string salted_universe_digest_hex = 3;</code>
     * @return The saltedUniverseDigestHex.
     */
    public String getSaltedUniverseDigestHex() {
      Object ref = saltedUniverseDigestHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        saltedUniverseDigestHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string salted_universe_digest_hex = 3;</code>
     * @return The bytes for saltedUniverseDigestHex.
     */
    public com.google.protobuf.ByteString
        getSaltedUniverseDigestHexBytes() {
      Object ref = saltedUniverseDigestHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        saltedUniverseDigestHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salted_universe_digest_hex = 3;</code>
     * @param value The saltedUniverseDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedUniverseDigestHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      saltedUniverseDigestHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salted_universe_digest_hex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaltedUniverseDigestHex() {
      
      saltedUniverseDigestHex_ = getDefaultInstance().getSaltedUniverseDigestHex();
      onChanged();
      return this;
    }
    /**
     * <code>string salted_universe_digest_hex = 3;</code>
     * @param value The bytes for saltedUniverseDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedUniverseDigestHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      saltedUniverseDigestHex_ = value;
      onChanged();
      return this;
    }

    private Object saltedComputerDigestHex_ = "";
    /**
     * <code>string salted_computer_digest_hex = 4;</code>
     * @return The saltedComputerDigestHex.
     */
    public String getSaltedComputerDigestHex() {
      Object ref = saltedComputerDigestHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        saltedComputerDigestHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string salted_computer_digest_hex = 4;</code>
     * @return The bytes for saltedComputerDigestHex.
     */
    public com.google.protobuf.ByteString
        getSaltedComputerDigestHexBytes() {
      Object ref = saltedComputerDigestHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        saltedComputerDigestHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salted_computer_digest_hex = 4;</code>
     * @param value The saltedComputerDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedComputerDigestHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      saltedComputerDigestHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salted_computer_digest_hex = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaltedComputerDigestHex() {
      
      saltedComputerDigestHex_ = getDefaultInstance().getSaltedComputerDigestHex();
      onChanged();
      return this;
    }
    /**
     * <code>string salted_computer_digest_hex = 4;</code>
     * @param value The bytes for saltedComputerDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setSaltedComputerDigestHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      saltedComputerDigestHex_ = value;
      onChanged();
      return this;
    }

    private Object expectedNextTickTxDigestHex_ = "";
    /**
     * <code>string expected_next_tick_tx_digest_hex = 5;</code>
     * @return The expectedNextTickTxDigestHex.
     */
    public String getExpectedNextTickTxDigestHex() {
      Object ref = expectedNextTickTxDigestHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        expectedNextTickTxDigestHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string expected_next_tick_tx_digest_hex = 5;</code>
     * @return The bytes for expectedNextTickTxDigestHex.
     */
    public com.google.protobuf.ByteString
        getExpectedNextTickTxDigestHexBytes() {
      Object ref = expectedNextTickTxDigestHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        expectedNextTickTxDigestHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expected_next_tick_tx_digest_hex = 5;</code>
     * @param value The expectedNextTickTxDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedNextTickTxDigestHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expectedNextTickTxDigestHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string expected_next_tick_tx_digest_hex = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpectedNextTickTxDigestHex() {
      
      expectedNextTickTxDigestHex_ = getDefaultInstance().getExpectedNextTickTxDigestHex();
      onChanged();
      return this;
    }
    /**
     * <code>string expected_next_tick_tx_digest_hex = 5;</code>
     * @param value The bytes for expectedNextTickTxDigestHex to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedNextTickTxDigestHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      expectedNextTickTxDigestHex_ = value;
      onChanged();
      return this;
    }

    private Object signatureHex_ = "";
    /**
     * <code>string signature_hex = 6;</code>
     * @return The signatureHex.
     */
    public String getSignatureHex() {
      Object ref = signatureHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signatureHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string signature_hex = 6;</code>
     * @return The bytes for signatureHex.
     */
    public com.google.protobuf.ByteString
        getSignatureHexBytes() {
      Object ref = signatureHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signatureHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string signature_hex = 6;</code>
     * @param value The signatureHex to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string signature_hex = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignatureHex() {
      
      signatureHex_ = getDefaultInstance().getSignatureHex();
      onChanged();
      return this;
    }
    /**
     * <code>string signature_hex = 6;</code>
     * @param value The bytes for signatureHex to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signatureHex_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qubic.archiver.archive.pb.QuorumDiff)
  }

  // @@protoc_insertion_point(class_scope:qubic.archiver.archive.pb.QuorumDiff)
  private static final QuorumDiff DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QuorumDiff();
  }

  public static QuorumDiff getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuorumDiff>
      PARSER = new com.google.protobuf.AbstractParser<QuorumDiff>() {
    @Override
    public QuorumDiff parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuorumDiff(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuorumDiff> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QuorumDiff> getParserForType() {
    return PARSER;
  }

  @Override
  public QuorumDiff getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

