// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

/**
 * Protobuf type {@code qubic.archiver.archive.pb.TickData}
 */
public final class TickData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qubic.archiver.archive.pb.TickData)
    TickDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TickData.newBuilder() to construct.
  private TickData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TickData() {
    varStruct_ = com.google.protobuf.ByteString.EMPTY;
    timeLock_ = com.google.protobuf.ByteString.EMPTY;
    transactionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    contractFees_ = emptyLongList();
    signatureHex_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TickData();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TickData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            computorIndex_ = input.readUInt32();
            break;
          }
          case 16: {

            epoch_ = input.readUInt32();
            break;
          }
          case 24: {

            tickNumber_ = input.readUInt32();
            break;
          }
          case 32: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 42: {

            varStruct_ = input.readBytes();
            break;
          }
          case 50: {

            timeLock_ = input.readBytes();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              transactionIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            transactionIds_.add(s);
            break;
          }
          case 64: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              contractFees_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            contractFees_.addLong(input.readInt64());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              contractFees_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              contractFees_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            signatureHex_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        transactionIds_ = transactionIds_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        contractFees_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_TickData_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_TickData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TickData.class, Builder.class);
  }

  public static final int COMPUTOR_INDEX_FIELD_NUMBER = 1;
  private int computorIndex_;
  /**
   * <code>uint32 computor_index = 1;</code>
   * @return The computorIndex.
   */
  @Override
  public int getComputorIndex() {
    return computorIndex_;
  }

  public static final int EPOCH_FIELD_NUMBER = 2;
  private int epoch_;
  /**
   * <code>uint32 epoch = 2;</code>
   * @return The epoch.
   */
  @Override
  public int getEpoch() {
    return epoch_;
  }

  public static final int TICK_NUMBER_FIELD_NUMBER = 3;
  private int tickNumber_;
  /**
   * <code>uint32 tick_number = 3;</code>
   * @return The tickNumber.
   */
  @Override
  public int getTickNumber() {
    return tickNumber_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int VAR_STRUCT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString varStruct_;
  /**
   * <code>bytes var_struct = 5;</code>
   * @return The varStruct.
   */
  @Override
  public com.google.protobuf.ByteString getVarStruct() {
    return varStruct_;
  }

  public static final int TIME_LOCK_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString timeLock_;
  /**
   * <code>bytes time_lock = 6;</code>
   * @return The timeLock.
   */
  @Override
  public com.google.protobuf.ByteString getTimeLock() {
    return timeLock_;
  }

  public static final int TRANSACTION_IDS_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList transactionIds_;
  /**
   * <code>repeated string transaction_ids = 7;</code>
   * @return A list containing the transactionIds.
   */
  public com.google.protobuf.ProtocolStringList
      getTransactionIdsList() {
    return transactionIds_;
  }
  /**
   * <code>repeated string transaction_ids = 7;</code>
   * @return The count of transactionIds.
   */
  public int getTransactionIdsCount() {
    return transactionIds_.size();
  }
  /**
   * <code>repeated string transaction_ids = 7;</code>
   * @param index The index of the element to return.
   * @return The transactionIds at the given index.
   */
  public String getTransactionIds(int index) {
    return transactionIds_.get(index);
  }
  /**
   * <code>repeated string transaction_ids = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the transactionIds at the given index.
   */
  public com.google.protobuf.ByteString
      getTransactionIdsBytes(int index) {
    return transactionIds_.getByteString(index);
  }

  public static final int CONTRACT_FEES_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.LongList contractFees_;
  /**
   * <code>repeated int64 contract_fees = 8;</code>
   * @return A list containing the contractFees.
   */
  @Override
  public java.util.List<Long>
      getContractFeesList() {
    return contractFees_;
  }
  /**
   * <code>repeated int64 contract_fees = 8;</code>
   * @return The count of contractFees.
   */
  public int getContractFeesCount() {
    return contractFees_.size();
  }
  /**
   * <code>repeated int64 contract_fees = 8;</code>
   * @param index The index of the element to return.
   * @return The contractFees at the given index.
   */
  public long getContractFees(int index) {
    return contractFees_.getLong(index);
  }
  private int contractFeesMemoizedSerializedSize = -1;

  public static final int SIGNATURE_HEX_FIELD_NUMBER = 9;
  private volatile Object signatureHex_;
  /**
   * <code>string signature_hex = 9;</code>
   * @return The signatureHex.
   */
  @Override
  public String getSignatureHex() {
    Object ref = signatureHex_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      signatureHex_ = s;
      return s;
    }
  }
  /**
   * <code>string signature_hex = 9;</code>
   * @return The bytes for signatureHex.
   */
  @Override
  public com.google.protobuf.ByteString
      getSignatureHexBytes() {
    Object ref = signatureHex_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      signatureHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (computorIndex_ != 0) {
      output.writeUInt32(1, computorIndex_);
    }
    if (epoch_ != 0) {
      output.writeUInt32(2, epoch_);
    }
    if (tickNumber_ != 0) {
      output.writeUInt32(3, tickNumber_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(4, timestamp_);
    }
    if (!varStruct_.isEmpty()) {
      output.writeBytes(5, varStruct_);
    }
    if (!timeLock_.isEmpty()) {
      output.writeBytes(6, timeLock_);
    }
    for (int i = 0; i < transactionIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, transactionIds_.getRaw(i));
    }
    if (getContractFeesList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(contractFeesMemoizedSerializedSize);
    }
    for (int i = 0; i < contractFees_.size(); i++) {
      output.writeInt64NoTag(contractFees_.getLong(i));
    }
    if (!getSignatureHexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, signatureHex_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (computorIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, computorIndex_);
    }
    if (epoch_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, epoch_);
    }
    if (tickNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, tickNumber_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, timestamp_);
    }
    if (!varStruct_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, varStruct_);
    }
    if (!timeLock_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, timeLock_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < transactionIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(transactionIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTransactionIdsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < contractFees_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(contractFees_.getLong(i));
      }
      size += dataSize;
      if (!getContractFeesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      contractFeesMemoizedSerializedSize = dataSize;
    }
    if (!getSignatureHexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, signatureHex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TickData)) {
      return super.equals(obj);
    }
    TickData other = (TickData) obj;

    if (getComputorIndex()
        != other.getComputorIndex()) return false;
    if (getEpoch()
        != other.getEpoch()) return false;
    if (getTickNumber()
        != other.getTickNumber()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getVarStruct()
        .equals(other.getVarStruct())) return false;
    if (!getTimeLock()
        .equals(other.getTimeLock())) return false;
    if (!getTransactionIdsList()
        .equals(other.getTransactionIdsList())) return false;
    if (!getContractFeesList()
        .equals(other.getContractFeesList())) return false;
    if (!getSignatureHex()
        .equals(other.getSignatureHex())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMPUTOR_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getComputorIndex();
    hash = (37 * hash) + EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + getEpoch();
    hash = (37 * hash) + TICK_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getTickNumber();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + VAR_STRUCT_FIELD_NUMBER;
    hash = (53 * hash) + getVarStruct().hashCode();
    hash = (37 * hash) + TIME_LOCK_FIELD_NUMBER;
    hash = (53 * hash) + getTimeLock().hashCode();
    if (getTransactionIdsCount() > 0) {
      hash = (37 * hash) + TRANSACTION_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionIdsList().hashCode();
    }
    if (getContractFeesCount() > 0) {
      hash = (37 * hash) + CONTRACT_FEES_FIELD_NUMBER;
      hash = (53 * hash) + getContractFeesList().hashCode();
    }
    hash = (37 * hash) + SIGNATURE_HEX_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureHex().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TickData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TickData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TickData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TickData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TickData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TickData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TickData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TickData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TickData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TickData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TickData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TickData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TickData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qubic.archiver.archive.pb.TickData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qubic.archiver.archive.pb.TickData)
      TickDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_TickData_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_TickData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TickData.class, Builder.class);
    }

    // Construct using org.qubic.archiver.proto.TickData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      computorIndex_ = 0;

      epoch_ = 0;

      tickNumber_ = 0;

      timestamp_ = 0L;

      varStruct_ = com.google.protobuf.ByteString.EMPTY;

      timeLock_ = com.google.protobuf.ByteString.EMPTY;

      transactionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      contractFees_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      signatureHex_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return QubicArchiverProtos.internal_static_qubic_archiver_archive_pb_TickData_descriptor;
    }

    @Override
    public TickData getDefaultInstanceForType() {
      return TickData.getDefaultInstance();
    }

    @Override
    public TickData build() {
      TickData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TickData buildPartial() {
      TickData result = new TickData(this);
      int from_bitField0_ = bitField0_;
      result.computorIndex_ = computorIndex_;
      result.epoch_ = epoch_;
      result.tickNumber_ = tickNumber_;
      result.timestamp_ = timestamp_;
      result.varStruct_ = varStruct_;
      result.timeLock_ = timeLock_;
      if (((bitField0_ & 0x00000001) != 0)) {
        transactionIds_ = transactionIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.transactionIds_ = transactionIds_;
      if (((bitField0_ & 0x00000002) != 0)) {
        contractFees_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.contractFees_ = contractFees_;
      result.signatureHex_ = signatureHex_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TickData) {
        return mergeFrom((TickData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TickData other) {
      if (other == TickData.getDefaultInstance()) return this;
      if (other.getComputorIndex() != 0) {
        setComputorIndex(other.getComputorIndex());
      }
      if (other.getEpoch() != 0) {
        setEpoch(other.getEpoch());
      }
      if (other.getTickNumber() != 0) {
        setTickNumber(other.getTickNumber());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getVarStruct() != com.google.protobuf.ByteString.EMPTY) {
        setVarStruct(other.getVarStruct());
      }
      if (other.getTimeLock() != com.google.protobuf.ByteString.EMPTY) {
        setTimeLock(other.getTimeLock());
      }
      if (!other.transactionIds_.isEmpty()) {
        if (transactionIds_.isEmpty()) {
          transactionIds_ = other.transactionIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTransactionIdsIsMutable();
          transactionIds_.addAll(other.transactionIds_);
        }
        onChanged();
      }
      if (!other.contractFees_.isEmpty()) {
        if (contractFees_.isEmpty()) {
          contractFees_ = other.contractFees_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureContractFeesIsMutable();
          contractFees_.addAll(other.contractFees_);
        }
        onChanged();
      }
      if (!other.getSignatureHex().isEmpty()) {
        signatureHex_ = other.signatureHex_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TickData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TickData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int computorIndex_ ;
    /**
     * <code>uint32 computor_index = 1;</code>
     * @return The computorIndex.
     */
    @Override
    public int getComputorIndex() {
      return computorIndex_;
    }
    /**
     * <code>uint32 computor_index = 1;</code>
     * @param value The computorIndex to set.
     * @return This builder for chaining.
     */
    public Builder setComputorIndex(int value) {
      
      computorIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 computor_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearComputorIndex() {
      
      computorIndex_ = 0;
      onChanged();
      return this;
    }

    private int epoch_ ;
    /**
     * <code>uint32 epoch = 2;</code>
     * @return The epoch.
     */
    @Override
    public int getEpoch() {
      return epoch_;
    }
    /**
     * <code>uint32 epoch = 2;</code>
     * @param value The epoch to set.
     * @return This builder for chaining.
     */
    public Builder setEpoch(int value) {
      
      epoch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 epoch = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpoch() {
      
      epoch_ = 0;
      onChanged();
      return this;
    }

    private int tickNumber_ ;
    /**
     * <code>uint32 tick_number = 3;</code>
     * @return The tickNumber.
     */
    @Override
    public int getTickNumber() {
      return tickNumber_;
    }
    /**
     * <code>uint32 tick_number = 3;</code>
     * @param value The tickNumber to set.
     * @return This builder for chaining.
     */
    public Builder setTickNumber(int value) {
      
      tickNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 tick_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTickNumber() {
      
      tickNumber_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString varStruct_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes var_struct = 5;</code>
     * @return The varStruct.
     */
    @Override
    public com.google.protobuf.ByteString getVarStruct() {
      return varStruct_;
    }
    /**
     * <code>bytes var_struct = 5;</code>
     * @param value The varStruct to set.
     * @return This builder for chaining.
     */
    public Builder setVarStruct(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      varStruct_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes var_struct = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVarStruct() {
      
      varStruct_ = getDefaultInstance().getVarStruct();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString timeLock_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes time_lock = 6;</code>
     * @return The timeLock.
     */
    @Override
    public com.google.protobuf.ByteString getTimeLock() {
      return timeLock_;
    }
    /**
     * <code>bytes time_lock = 6;</code>
     * @param value The timeLock to set.
     * @return This builder for chaining.
     */
    public Builder setTimeLock(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeLock_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes time_lock = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeLock() {
      
      timeLock_ = getDefaultInstance().getTimeLock();
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList transactionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTransactionIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transactionIds_ = new com.google.protobuf.LazyStringArrayList(transactionIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @return A list containing the transactionIds.
     */
    public com.google.protobuf.ProtocolStringList
        getTransactionIdsList() {
      return transactionIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @return The count of transactionIds.
     */
    public int getTransactionIdsCount() {
      return transactionIds_.size();
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @param index The index of the element to return.
     * @return The transactionIds at the given index.
     */
    public String getTransactionIds(int index) {
      return transactionIds_.get(index);
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the transactionIds at the given index.
     */
    public com.google.protobuf.ByteString
        getTransactionIdsBytes(int index) {
      return transactionIds_.getByteString(index);
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @param index The index to set the value at.
     * @param value The transactionIds to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIds(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionIdsIsMutable();
      transactionIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @param value The transactionIds to add.
     * @return This builder for chaining.
     */
    public Builder addTransactionIds(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionIdsIsMutable();
      transactionIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @param values The transactionIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllTransactionIds(
        Iterable<String> values) {
      ensureTransactionIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, transactionIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionIds() {
      transactionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string transaction_ids = 7;</code>
     * @param value The bytes of the transactionIds to add.
     * @return This builder for chaining.
     */
    public Builder addTransactionIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTransactionIdsIsMutable();
      transactionIds_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList contractFees_ = emptyLongList();
    private void ensureContractFeesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        contractFees_ = mutableCopy(contractFees_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @return A list containing the contractFees.
     */
    public java.util.List<Long>
        getContractFeesList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(contractFees_) : contractFees_;
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @return The count of contractFees.
     */
    public int getContractFeesCount() {
      return contractFees_.size();
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @param index The index of the element to return.
     * @return The contractFees at the given index.
     */
    public long getContractFees(int index) {
      return contractFees_.getLong(index);
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @param index The index to set the value at.
     * @param value The contractFees to set.
     * @return This builder for chaining.
     */
    public Builder setContractFees(
        int index, long value) {
      ensureContractFeesIsMutable();
      contractFees_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @param value The contractFees to add.
     * @return This builder for chaining.
     */
    public Builder addContractFees(long value) {
      ensureContractFeesIsMutable();
      contractFees_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @param values The contractFees to add.
     * @return This builder for chaining.
     */
    public Builder addAllContractFees(
        Iterable<? extends Long> values) {
      ensureContractFeesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, contractFees_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 contract_fees = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractFees() {
      contractFees_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private Object signatureHex_ = "";
    /**
     * <code>string signature_hex = 9;</code>
     * @return The signatureHex.
     */
    public String getSignatureHex() {
      Object ref = signatureHex_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signatureHex_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string signature_hex = 9;</code>
     * @return The bytes for signatureHex.
     */
    public com.google.protobuf.ByteString
        getSignatureHexBytes() {
      Object ref = signatureHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signatureHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string signature_hex = 9;</code>
     * @param value The signatureHex to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureHex(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signatureHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string signature_hex = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignatureHex() {
      
      signatureHex_ = getDefaultInstance().getSignatureHex();
      onChanged();
      return this;
    }
    /**
     * <code>string signature_hex = 9;</code>
     * @param value The bytes for signatureHex to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signatureHex_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qubic.archiver.archive.pb.TickData)
  }

  // @@protoc_insertion_point(class_scope:qubic.archiver.archive.pb.TickData)
  private static final TickData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TickData();
  }

  public static TickData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TickData>
      PARSER = new com.google.protobuf.AbstractParser<TickData>() {
    @Override
    public TickData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TickData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TickData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TickData> getParserForType() {
    return PARSER;
  }

  @Override
  public TickData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

