// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface TransferTransactionsPerTickOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.TransferTransactionsPerTick)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 tick_number = 1;</code>
   * @return The tickNumber.
   */
  int getTickNumber();

  /**
   * <code>string identity = 2;</code>
   * @return The identity.
   */
  java.lang.String getIdentity();
  /**
   * <code>string identity = 2;</code>
   * @return The bytes for identity.
   */
  com.google.protobuf.ByteString
      getIdentityBytes();

  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 3;</code>
   */
  java.util.List<org.qubic.archiver.proto.Transaction> 
      getTransactionsList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 3;</code>
   */
  org.qubic.archiver.proto.Transaction getTransactions(int index);
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 3;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 3;</code>
   */
  java.util.List<? extends org.qubic.archiver.proto.TransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .qubic.archiver.archive.pb.Transaction transactions = 3;</code>
   */
  org.qubic.archiver.proto.TransactionOrBuilder getTransactionsOrBuilder(
      int index);
}
