// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

package org.qubic.archiver.proto;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qubic.archiver.archive.pb.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source_id = 1;</code>
   * @return The sourceId.
   */
  String getSourceId();
  /**
   * <code>string source_id = 1;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string dest_id = 2;</code>
   * @return The destId.
   */
  String getDestId();
  /**
   * <code>string dest_id = 2;</code>
   * @return The bytes for destId.
   */
  com.google.protobuf.ByteString
      getDestIdBytes();

  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>uint32 tick_number = 4;</code>
   * @return The tickNumber.
   */
  int getTickNumber();

  /**
   * <code>uint32 input_type = 5;</code>
   * @return The inputType.
   */
  int getInputType();

  /**
   * <code>uint32 input_size = 6;</code>
   * @return The inputSize.
   */
  int getInputSize();

  /**
   * <code>string input_hex = 7;</code>
   * @return The inputHex.
   */
  String getInputHex();
  /**
   * <code>string input_hex = 7;</code>
   * @return The bytes for inputHex.
   */
  com.google.protobuf.ByteString
      getInputHexBytes();

  /**
   * <code>string signature_hex = 8;</code>
   * @return The signatureHex.
   */
  String getSignatureHex();
  /**
   * <code>string signature_hex = 8;</code>
   * @return The bytes for signatureHex.
   */
  com.google.protobuf.ByteString
      getSignatureHexBytes();

  /**
   * <code>string tx_id = 9;</code>
   * @return The txId.
   */
  String getTxId();
  /**
   * <code>string tx_id = 9;</code>
   * @return The bytes for txId.
   */
  com.google.protobuf.ByteString
      getTxIdBytes();
}
